version: '3.1'
services:
    item-server:
        container_name: item-server
        build:
            context: item
            dockerfile: Dockerfile
        image: item-server:latest
        ports:
            - 16666:8080
        networks:
            - spring-cloud-network
            - axon-demo
    user-server:
        container_name: user-server
        build:
            context: user
            dockerfile: Dockerfile
        image: user-server:latest
        ports:
            - 19999:8081
        networks:
            - spring-cloud-network
            - axon-demo
    purchaseLog-server:
        container_name: purchaseLog-server
        build:
            context: purchaseLog
            dockerfile: Dockerfile
        image: purchaselog-server:latest
        ports:
            - 17777:8082
        networks:
            - spring-cloud-network
            - axon-demo
    cart-server:
        container_name: cart-server
        build:
            context: cart
            dockerfile: Dockerfile
        depends_on: 
            item-server:
               condition: service_started
        image: cart-server:latest
        ports:
            - 18888:8083
        networks:
            - spring-cloud-network
            - axon-demo
    main-server:
        container_name: main-server
        build:
            context: main
            dockerfile: Dockerfile
        image: main-server:latest
        ports:
            - 15555:8084
        networks:
            - spring-cloud-network
    favourite-server:
        container_name: favourite-server
        build:
            context: favourite
            dockerfile: Dockerfile
        image: favourite-server:latest
        ports:
            - 14444:8085
        networks:
            - spring-cloud-network
    axonserver:
        image: axoniq/axonserver
        hostname: axonserver
        volumes:
            - axonserver-data:/data
            - axonserver-events:/eventdata
            - axonserver-config:/config:ro
        ports:
            - '8024:8024'
            - '8124:8124'
            - '8224:8224'
        networks:
            - axon-demo
volumes:
        axonserver-data:
        axonserver-events:
        axonserver-config:
networks:
    spring-cloud-network:
        driver: bridge
    axon-demo:
        driver: bridge